/// All known OpCodes of the Chip8,
/// as well as one variant for invalid opcodes
pub(crate) enum OpCode {
    ClearScreen(u16),
    Return(u16),
    Jump(u16),
    Call(u16),
    SkipIfRegisterEqualsValue(u16),
    SkipIfRegisterNotEqualsValue(u16),
    SkipIfRegistersAreEqual(u16),
    Load(u16),
    Add(u16),
    LoadRegister(u16),
    Or(u16),
    And(u16),
    Xor(u16),
    AddWithCarry(u16),
    Sub(u16),
    Shr(u16), // What is this?
    SubInverse(u16),
    Shl(u16), // What is this?
    SkipIfRegistersAreNotEqual(u16),
    LoadI(u16),
    JumpV0(u16),
    RandomAnd(u16),
    DrawSprite(u16),
    SkipIfKeyPressed(u16),
    SkipIfKeyNotPressed(u16),
    LoadDealay(u16),
    WaitKeyPress(u16),
    SetDelay(u16),
    SetSound(u16),
    AddI(u16),
    LoadSprite(u16),
    LoadBcd(u16),
    DumpAll(u16),
    LoadAll(u16),
    Invalid,
}
